BotSelfConfig:
  host: "127.0.0.1"
  port: 8080
  debug: false
  superusers: ["2743218818"]
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  command_start: ["/"]
  command_sep: ["."]
  session_expire_timeout: 60
  proxy: ""  # 请参考文档
  server_status_only_superusers:false

InlineGoCQHTTP:
  enabled: true
  accounts: # 可多个账号，具体请参考文档
    - uin: 
      password: 
      protocol: 5
  
  download_domain: ""
  download_version: "v1.0.0-rc1"

SauceNAO:
  key: ""

Setu:
  reverse_proxy: true # 请参考文档
  reverse_proxy_domain: "i.pixiv.re"
